---
- name: Apache Playbook
  hosts: apache
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install Apache (httpd)
      yum:
        name: httpd
        state: latest

    - name: Stop Apache (httpd), if started
      ignore_errors: yes
      ansible.builtin.service:
        name: httpd
        state: stopped

    - name: Configure Apache reverse proxy
      copy:
        src: data/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: 0644

    - name: Restart and enable Apache (httpd)
      ignore_errors: yes
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: yes

- name: Node Playbook
  hosts: node
  remote_user: ec2-user

  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      become: true

    - name: Add NodeSource to system
      ansible.builtin.shell:
        cmd: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -
        chdir: /home/ec2-user

    - name: Install necessary software
      yum:
        name:
          - nodejs-16.16.0-1nodesource
          - git
          - gcc-c++
          - make
      become: true

    - name: Install pm2
      ansible.builtin.shell:
        cmd: npm install pm2@latest -g
        chdir: /home/ec2-user
      become: true

    - name: Start pm2
      ansible.builtin.shell:
        cmd: pm2 startup
        chdir: /home/ec2-user

    - name: Set pm2 path
      ansible.builtin.shell:
        cmd: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ec2-user --hp /home/ec2-user
        chdir: /home/ec2-user
      become: true

    - name: git clone / pull
      ignore_errors: yes
      git:
        repo: https://github.com/opedani/webapp-opedani.git
        dest: /home/ec2-user/webapp-opedani
        single_branch: yes
        version: development

    - name: npm install
      ignore_errors: yes
      ansible.builtin.shell:
        cmd: npm install
        chdir: /home/ec2-user/webapp-opedani

    - name: Copy pm2 ecosystem file
      copy:
        src: data/ecosystem.config.js
        dest: /home/ec2-user/ecosystem.config.js
        owner: ec2-user
        group: ec2-user
        mode: 0664

    - name: pm2 reload
      ansible.builtin.shell:
        cmd: pm2 reload ecosystem.config.js
        chdir: /home/ec2-user

    - name: pm2 save
      ansible.builtin.shell:
        cmd: pm2 save
        chdir: /home/ec2-user
