---
- name: Playbook
  hosts: node
  remote_user: ec2-user

  tasks:
    - name: Git Pull
      git:
        repo: https://github.com/opedani/webapp-opedani.git
        dest: /home/ec2-user/webapp-opedani
        single_branch: yes
        version: master
