name: 'Ansible'

# Occurs on pushes to master
on:
  push:
    branches:
      - master

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: production

    # Always use bash shell and start in ./ansible directory
    defaults:
      run:
        shell: bash
        working-directory: ./ansible

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      run: ansible-playbook playbook.yml
