name: 'Ansible'

# Occurs on pushes to master
on:
  push:
    branches:
      - master

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2.5.0
      with:
        # Required, playbook filepath
        playbook: playbook.yml
        # Optional, directory where playbooks live
        directory: ./ansible
        # Optional, SSH private key
        key: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}
        # Optional, additional flags to pass to ansible-playbook
        options: |
          --inventory .inventory
          --limit node
          --verbose
