name: 'CI CD'

# Occurs on pushes to master branch
on:
  push:
    branches:
      - master

jobs:
  ci_cd:
    name: 'CI CD'
    runs-on: ubuntu-latest
    environment: production

    # Always use Bash shell and start in ./terraform subdirectory
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Install the latest Terraform CLI and configure it with a Terraform Cloud API token
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API }}

    # Run "terraform init"
    - name: Terraform Init
      run: terraform init -backend-config=production_backend.conf

    # Run "terraform fmt -check -diff"
    - name: Terraform Format
      run: terraform fmt -check -diff

    # Run "terraform validate"
    - name: Terraform Validate
      run: terraform validate

    # Run "terraform apply"
    - name: Terraform Apply
      run: terraform apply

    # Run the Ansible playbook
    - name: Run Playbooks
      uses: dawidd6/action-ansible-playbook@v2.5.0
      with:
        playbook: playbook.yml
        directory: ../ansible
        key: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}
        options: |
          --inventory .inventory
