name: 'CI CD Development'

# Occurs on pushes to development branch
on:
  push:
    branches:
      development

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development

    # Always use Bash shell and start in ./cicd_dev/terraform subdirectory
    defaults:
      run:
        shell: bash
        working-directory: ./cicd_dev/terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Install the latest Terraform CLI and configure it with a Terraform Cloud API token
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API }}

    # Run "terraform init"
    - name: Terraform Init
      run: terraform init

    # Run "terraform validate"
    - name: Terraform Validate
      run: terraform validate

    # Run "terraform apply"
    - name: Terraform Apply
      run: terraform apply

  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: development
    needs: terraform

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run the Ansible playbook
      - name: Run Playbooks
        uses: dawidd6/action-ansible-playbook@v2.6.0
        with:
          playbook: playbook.yml
          directory: ./cicd_dev/ansible
          key: ${{secrets.ANSIBLE_DEV_SSH_PRIVATE_KEY}}
          options: |
            --inventory .inventory
            --verbose
            --diff
