name: 'Terraform'

# Occurs on pushes to any branch
on:
  push:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Always use Bash shell and start in ./terraform subdirectory
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest Terraform CLI and configure it with a Terraform Cloud API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API }}

    # Verify Terraform code is formatted properly
    - name: Terraform Format
      run: terraform fmt -check

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Run "terraform plan"
    - name: Terraform Plan
      run: terraform plan -input=false

    # Run "terraform apply" for pushes to master branch
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      run: terraform apply
